BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "usuarios" (
	"id"	INT AUTO_INCREMENT,
	"nombre"	VARCHAR(100) NOT NULL,
	"email"	VARCHAR(100) NOT NULL UNIQUE,
	"contrasena"	VARCHAR(255) NOT NULL,
	PRIMARY KEY("id")
);
COMMIT;
